nom : learn-github-actions 
nom-exécution : ${{ github.actor }} apprend GitHub Actions 
sur : [push] 
tâches : 
  check-bats-version : 
    s'exécute sur : ubuntu-latest 
    étapes : 
      - utilise : actions/checkout@v5 
      - utilise : actions/setup-node@v4 
        avec : 
          node-version : '20' 
      - exécuter : npm install -g bats 
      - exécuter : bats -v
